name: nabelli_ecommerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  animations:
  cached_network_image: any
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: any
  firebase_core: any
  firebase_messaging: ^11.2.6
  flutter_iconly: ^1.0.2
  flutter_local_notifications: any
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^1.0.3
  get: 4.6.5
  get_storage: 2.0.3
  google_nav_bar: ^5.0.6
  http: any
  lottie: ^1.2.1
  pull_to_refresh: ^2.0.0
  restart_app: ^1.1.0
  share: any
  url_launcher: 6.1.6
  vibration: ^1.7.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/categoryIcons/
    - assets/lottie/
    - assets/image/
    - assets/image/banners/
    - assets/image/brands/
    - assets/image/water/
  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true
